repo_name: accumulation_agent
repo_id: d9c145d5-9033-410a-b65d-c678f2fe16f9
harness_home: C:\Users\trait\.harness
registered_at: 2026-06-10T13:35:56.833Z
remote_url: https://github.com/tamtiger/accumulation_agent.git
