repo_name: accumulation_agent
repo_id: 47d8c58b-2e8d-407f-9eea-f426c4526720
harness_home: C:\Users\trait\.harness
registered_at: 2026-06-12T14:26:44.602Z
remote_url: https://github.com/tamtiger/accumulation_agent.git
